experiment_name: ssl_hyperparameter_tuning

experiment_version: "2.0" 

paths:
  data_root: "../../../data/upftfg26/apujols/processed/original"
  labels_csv: "../../../data/upftfg26/apujols/processed/dataset_36164.csv"
  output_dir: "training/hyperparameter_tunning/optuna_logs/"

model:
  backbone_dim: 512
  hidden_dim: 128
  projection_dim: 1024

training:
  batch_size: 64
  num_epochs: 40
  patience: 5
  cutoff_ratio: 0.001
  learning_rate: 0.001
  temperature: 0.5
  num_iterations: 2000
  use_image_augs: False

optuna:
  n_trials: 50