experiment_name: ssl_input_images

experiment_version: "2.5" # v2.1 - 2-5" changing the input folder in 'data_root'

paths:
  data_root: "../../../data/upftfg26/apujols/processed/percentile_stretch" # original (2.1), global_threshold (2.2), meteors_stretch (2.3), min_max_stretch (2.4), percentile_stretch (2.5)
  labels_csv: "../../../data/upftfg26/apujols/processed/dataset_36164.csv"
  output_dir: "logs/training/"

model:
  backbone_dim: 512
  hidden_dim: 128
  projection_dim: 1024

training:
  batch_size: 64
  num_epochs: 15
  patience: 5
  cutoff_ratio: 0.001
  learning_rate: 0.001
  temperature: 0.5
